source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'sinatra-partial'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'activerecord', '3.2.17'
gem 'sinatra-activerecord'
gem 'compass'
gem 'bootstrap'
gem 'font-awesome-sass'
gem 'dotenv'
gem 'capistrano'
gem 'capistrano-passenger'
gem 'capistrano-rbenv', '~> 2.0'
gem 'capistrano-bundler'
gem 'thin'
gem 'sys-filesystem'
gem 'rspec'
gem 'rack-test', :require => "rack/test"
gem 'simplecov', :require => false
gem 'capistrano-rails'
